/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq;


import com.hjr.framework.appollo.jooq.tables.Picture;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Picture.PICTURE, new OrderField[] { Picture.PICTURE.ID }, true);
    }
}
