/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq;


import com.hjr.framework.appollo.jooq.tables.Picture;
import com.hjr.framework.appollo.jooq.tables.records.PictureRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PictureRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<PictureRecord> CONSTRAINT_8 = Internal.createUniqueKey(Picture.PICTURE, "CONSTRAINT_8", Picture.PICTURE.ID);
    }
}
