/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq;


import com.hjr.framework.appollo.jooq.tables.Picture;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.PICTURE</code>.
     */
    public static final Picture PICTURE = com.hjr.framework.appollo.jooq.tables.Picture.PICTURE;
}
