/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq.tables.pojos;


import com.hjr.framework.appollo.jooq.tables.interfaces.IPicture;

import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Picture implements IPicture {

    private static final long serialVersionUID = 776110739;

    private Long      id;
    private String    srcSite;
    private String    srcUrl;
    private String    url;
    private String    name;
    private String    savePath;
    private Byte      yn;
    private LocalDate createTime;
    private LocalDate modifyTime;
    private String    tag;
    private String    type;
    private String    desc;
    private Integer   shareNum;
    private Integer   viewNum;
    private Integer   likeNum;
    private Integer   saveNum;

    public Picture() {}

    public Picture(Picture value) {
        this.id = value.id;
        this.srcSite = value.srcSite;
        this.srcUrl = value.srcUrl;
        this.url = value.url;
        this.name = value.name;
        this.savePath = value.savePath;
        this.yn = value.yn;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.tag = value.tag;
        this.type = value.type;
        this.desc = value.desc;
        this.shareNum = value.shareNum;
        this.viewNum = value.viewNum;
        this.likeNum = value.likeNum;
        this.saveNum = value.saveNum;
    }

    public Picture(
        Long      id,
        String    srcSite,
        String    srcUrl,
        String    url,
        String    name,
        String    savePath,
        Byte      yn,
        LocalDate createTime,
        LocalDate modifyTime,
        String    tag,
        String    type,
        String    desc,
        Integer   shareNum,
        Integer   viewNum,
        Integer   likeNum,
        Integer   saveNum
    ) {
        this.id = id;
        this.srcSite = srcSite;
        this.srcUrl = srcUrl;
        this.url = url;
        this.name = name;
        this.savePath = savePath;
        this.yn = yn;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.tag = tag;
        this.type = type;
        this.desc = desc;
        this.shareNum = shareNum;
        this.viewNum = viewNum;
        this.likeNum = likeNum;
        this.saveNum = saveNum;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getSrcSite() {
        return this.srcSite;
    }

    @Override
    public void setSrcSite(String srcSite) {
        this.srcSite = srcSite;
    }

    @Override
    public String getSrcUrl() {
        return this.srcUrl;
    }

    @Override
    public void setSrcUrl(String srcUrl) {
        this.srcUrl = srcUrl;
    }

    @Override
    public String getUrl() {
        return this.url;
    }

    @Override
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getSavePath() {
        return this.savePath;
    }

    @Override
    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

    @Override
    public Byte getYn() {
        return this.yn;
    }

    @Override
    public void setYn(Byte yn) {
        this.yn = yn;
    }

    @Override
    public LocalDate getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    @Override
    public LocalDate getModifyTime() {
        return this.modifyTime;
    }

    @Override
    public void setModifyTime(LocalDate modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String getTag() {
        return this.tag;
    }

    @Override
    public void setTag(String tag) {
        this.tag = tag;
    }

    @Override
    public String getType() {
        return this.type;
    }

    @Override
    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String getDesc() {
        return this.desc;
    }

    @Override
    public void setDesc(String desc) {
        this.desc = desc;
    }

    @Override
    public Integer getShareNum() {
        return this.shareNum;
    }

    @Override
    public void setShareNum(Integer shareNum) {
        this.shareNum = shareNum;
    }

    @Override
    public Integer getViewNum() {
        return this.viewNum;
    }

    @Override
    public void setViewNum(Integer viewNum) {
        this.viewNum = viewNum;
    }

    @Override
    public Integer getLikeNum() {
        return this.likeNum;
    }

    @Override
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    @Override
    public Integer getSaveNum() {
        return this.saveNum;
    }

    @Override
    public void setSaveNum(Integer saveNum) {
        this.saveNum = saveNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Picture (");

        sb.append(id);
        sb.append(", ").append(srcSite);
        sb.append(", ").append(srcUrl);
        sb.append(", ").append(url);
        sb.append(", ").append(name);
        sb.append(", ").append(savePath);
        sb.append(", ").append(yn);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(tag);
        sb.append(", ").append(type);
        sb.append(", ").append(desc);
        sb.append(", ").append(shareNum);
        sb.append(", ").append(viewNum);
        sb.append(", ").append(likeNum);
        sb.append(", ").append(saveNum);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IPicture from) {
        setId(from.getId());
        setSrcSite(from.getSrcSite());
        setSrcUrl(from.getSrcUrl());
        setUrl(from.getUrl());
        setName(from.getName());
        setSavePath(from.getSavePath());
        setYn(from.getYn());
        setCreateTime(from.getCreateTime());
        setModifyTime(from.getModifyTime());
        setTag(from.getTag());
        setType(from.getType());
        setDesc(from.getDesc());
        setShareNum(from.getShareNum());
        setViewNum(from.getViewNum());
        setLikeNum(from.getLikeNum());
        setSaveNum(from.getSaveNum());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IPicture> E into(E into) {
        into.from(this);
        return into;
    }
}
