/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq.tables.daos;


import com.hjr.framework.appollo.jooq.tables.Picture;
import com.hjr.framework.appollo.jooq.tables.records.PictureRecord;

import java.time.LocalDate;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PictureDao extends DAOImpl<PictureRecord, com.hjr.framework.appollo.jooq.tables.pojos.Picture, Long> {

    /**
     * Create a new PictureDao without any configuration
     */
    public PictureDao() {
        super(Picture.PICTURE, com.hjr.framework.appollo.jooq.tables.pojos.Picture.class);
    }

    /**
     * Create a new PictureDao with an attached configuration
     */
    @Autowired
    public PictureDao(Configuration configuration) {
        super(Picture.PICTURE, com.hjr.framework.appollo.jooq.tables.pojos.Picture.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.hjr.framework.appollo.jooq.tables.pojos.Picture object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchById(Long... values) {
        return fetch(Picture.PICTURE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.hjr.framework.appollo.jooq.tables.pojos.Picture fetchOneById(Long value) {
        return fetchOne(Picture.PICTURE.ID, value);
    }

    /**
     * Fetch records that have <code>SRC_SITE IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchBySrcSite(String... values) {
        return fetch(Picture.PICTURE.SRC_SITE, values);
    }

    /**
     * Fetch records that have <code>SRC_URL IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchBySrcUrl(String... values) {
        return fetch(Picture.PICTURE.SRC_URL, values);
    }

    /**
     * Fetch records that have <code>URL IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByUrl(String... values) {
        return fetch(Picture.PICTURE.URL, values);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByName(String... values) {
        return fetch(Picture.PICTURE.NAME, values);
    }

    /**
     * Fetch records that have <code>SAVE_PATH IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchBySavePath(String... values) {
        return fetch(Picture.PICTURE.SAVE_PATH, values);
    }

    /**
     * Fetch records that have <code>YN IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByYn(Byte... values) {
        return fetch(Picture.PICTURE.YN, values);
    }

    /**
     * Fetch records that have <code>CREATE_TIME IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByCreateTime(LocalDate... values) {
        return fetch(Picture.PICTURE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFY_TIME IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByModifyTime(LocalDate... values) {
        return fetch(Picture.PICTURE.MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>TAG IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByTag(String... values) {
        return fetch(Picture.PICTURE.TAG, values);
    }

    /**
     * Fetch records that have <code>TYPE IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByType(String... values) {
        return fetch(Picture.PICTURE.TYPE, values);
    }

    /**
     * Fetch records that have <code>DESC IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByDesc(String... values) {
        return fetch(Picture.PICTURE.DESC, values);
    }

    /**
     * Fetch records that have <code>SHARE_NUM IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByShareNum(Integer... values) {
        return fetch(Picture.PICTURE.SHARE_NUM, values);
    }

    /**
     * Fetch records that have <code>VIEW_NUM IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByViewNum(Integer... values) {
        return fetch(Picture.PICTURE.VIEW_NUM, values);
    }

    /**
     * Fetch records that have <code>LIKE_NUM IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchByLikeNum(Integer... values) {
        return fetch(Picture.PICTURE.LIKE_NUM, values);
    }

    /**
     * Fetch records that have <code>SAVE_NUM IN (values)</code>
     */
    public List<com.hjr.framework.appollo.jooq.tables.pojos.Picture> fetchBySaveNum(Integer... values) {
        return fetch(Picture.PICTURE.SAVE_NUM, values);
    }
}
