package com.hjr.framework.appollo.spider.mybatis.mapper;

import com.hjr.framework.appollo.spider.domain.CrawlDataParseRule;
import com.hjr.framework.appollo.spider.domain.CrawlDataParseRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlDataParseRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    long countByExample(CrawlDataParseRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int deleteByExample(CrawlDataParseRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int insert(CrawlDataParseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int insertSelective(CrawlDataParseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    List<CrawlDataParseRule> selectByExample(CrawlDataParseRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    CrawlDataParseRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrawlDataParseRule record, @Param("example") CrawlDataParseRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int updateByExample(@Param("record") CrawlDataParseRule record, @Param("example") CrawlDataParseRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int updateByPrimaryKeySelective(CrawlDataParseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    int updateByPrimaryKey(CrawlDataParseRule record);
}