package com.hjr.framework.appollo.spider.mybatis.mapper;

import com.hjr.framework.appollo.spider.domain.CrawlResult;
import com.hjr.framework.appollo.spider.domain.CrawlResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    long countByExample(CrawlResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int deleteByExample(CrawlResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int insert(CrawlResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int insertSelective(CrawlResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    List<CrawlResult> selectByExample(CrawlResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    CrawlResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrawlResult record, @Param("example") CrawlResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int updateByExample(@Param("record") CrawlResult record, @Param("example") CrawlResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int updateByPrimaryKeySelective(CrawlResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_RESULT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    int updateByPrimaryKey(CrawlResult record);
}