package com.hjr.framework.appollo.spider.mybatis.mapper;

import com.hjr.framework.appollo.spider.domain.CrawlTask;
import com.hjr.framework.appollo.spider.domain.CrawlTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    long countByExample(CrawlTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int deleteByExample(CrawlTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int insert(CrawlTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int insertSelective(CrawlTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    List<CrawlTask> selectByExample(CrawlTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    CrawlTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrawlTask record, @Param("example") CrawlTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int updateByExample(@Param("record") CrawlTask record, @Param("example") CrawlTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int updateByPrimaryKeySelective(CrawlTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_TASK
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    int updateByPrimaryKey(CrawlTask record);
}