package com.hjr.framework.appollo.spider.mybatis.mapper;

import com.hjr.framework.appollo.spider.domain.Picture;
import com.hjr.framework.appollo.spider.domain.PictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    long countByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int deleteByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int insertSelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    List<Picture> selectByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    Picture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int updateByExample(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int updateByPrimaryKeySelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PICTURE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    int updateByPrimaryKey(Picture record);
}