/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq.tables.records;


import com.hjr.framework.appollo.jooq.tables.Picture;
import com.hjr.framework.appollo.jooq.tables.interfaces.IPicture;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PictureRecord extends UpdatableRecordImpl<PictureRecord> implements Record16<Long, String, String, String, String, String, Byte, LocalDate, LocalDate, String, String, String, Integer, Integer, Integer, Integer>, IPicture {

    private static final long serialVersionUID = -1901359417;

    /**
     * Setter for <code>PUBLIC.PICTURE.ID</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.ID</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.SRC_SITE</code>.
     */
    @Override
    public void setSrcSite(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.SRC_SITE</code>.
     */
    @Override
    public String getSrcSite() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.SRC_URL</code>.
     */
    @Override
    public void setSrcUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.SRC_URL</code>.
     */
    @Override
    public String getSrcUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.URL</code>.
     */
    @Override
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.URL</code>.
     */
    @Override
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.NAME</code>.
     */
    @Override
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.NAME</code>.
     */
    @Override
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.SAVE_PATH</code>.
     */
    @Override
    public void setSavePath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.SAVE_PATH</code>.
     */
    @Override
    public String getSavePath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.YN</code>.
     */
    @Override
    public void setYn(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.YN</code>.
     */
    @Override
    public Byte getYn() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.CREATE_TIME</code>.
     */
    @Override
    public void setCreateTime(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.CREATE_TIME</code>.
     */
    @Override
    public LocalDate getCreateTime() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.MODIFY_TIME</code>.
     */
    @Override
    public void setModifyTime(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.MODIFY_TIME</code>.
     */
    @Override
    public LocalDate getModifyTime() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.TAG</code>.
     */
    @Override
    public void setTag(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.TAG</code>.
     */
    @Override
    public String getTag() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.TYPE</code>.
     */
    @Override
    public void setType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.TYPE</code>.
     */
    @Override
    public String getType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.DESC</code>.
     */
    @Override
    public void setDesc(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.DESC</code>.
     */
    @Override
    public String getDesc() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.SHARE_NUM</code>.
     */
    @Override
    public void setShareNum(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.SHARE_NUM</code>.
     */
    @Override
    public Integer getShareNum() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.VIEW_NUM</code>.
     */
    @Override
    public void setViewNum(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.VIEW_NUM</code>.
     */
    @Override
    public Integer getViewNum() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.LIKE_NUM</code>.
     */
    @Override
    public void setLikeNum(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.LIKE_NUM</code>.
     */
    @Override
    public Integer getLikeNum() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>PUBLIC.PICTURE.SAVE_NUM</code>.
     */
    @Override
    public void setSaveNum(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.PICTURE.SAVE_NUM</code>.
     */
    @Override
    public Integer getSaveNum() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, String, String, Byte, LocalDate, LocalDate, String, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, String, String, Byte, LocalDate, LocalDate, String, String, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Picture.PICTURE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Picture.PICTURE.SRC_SITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Picture.PICTURE.SRC_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Picture.PICTURE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Picture.PICTURE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Picture.PICTURE.SAVE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Picture.PICTURE.YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field8() {
        return Picture.PICTURE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field9() {
        return Picture.PICTURE.MODIFY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Picture.PICTURE.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Picture.PICTURE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Picture.PICTURE.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Picture.PICTURE.SHARE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Picture.PICTURE.VIEW_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Picture.PICTURE.LIKE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return Picture.PICTURE.SAVE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSrcSite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSrcUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSavePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component9() {
        return getModifyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getShareNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getViewNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getLikeNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getSaveNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSrcSite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSrcUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSavePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value9() {
        return getModifyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getShareNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getViewNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getLikeNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getSaveNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value2(String value) {
        setSrcSite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value3(String value) {
        setSrcUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value6(String value) {
        setSavePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value7(Byte value) {
        setYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value8(LocalDate value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value9(LocalDate value) {
        setModifyTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value10(String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value11(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value12(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value13(Integer value) {
        setShareNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value14(Integer value) {
        setViewNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value15(Integer value) {
        setLikeNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value16(Integer value) {
        setSaveNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Byte value7, LocalDate value8, LocalDate value9, String value10, String value11, String value12, Integer value13, Integer value14, Integer value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IPicture from) {
        setId(from.getId());
        setSrcSite(from.getSrcSite());
        setSrcUrl(from.getSrcUrl());
        setUrl(from.getUrl());
        setName(from.getName());
        setSavePath(from.getSavePath());
        setYn(from.getYn());
        setCreateTime(from.getCreateTime());
        setModifyTime(from.getModifyTime());
        setTag(from.getTag());
        setType(from.getType());
        setDesc(from.getDesc());
        setShareNum(from.getShareNum());
        setViewNum(from.getViewNum());
        setLikeNum(from.getLikeNum());
        setSaveNum(from.getSaveNum());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IPicture> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PictureRecord
     */
    public PictureRecord() {
        super(Picture.PICTURE);
    }

    /**
     * Create a detached, initialised PictureRecord
     */
    public PictureRecord(Long id, String srcSite, String srcUrl, String url, String name, String savePath, Byte yn, LocalDate createTime, LocalDate modifyTime, String tag, String type, String desc, Integer shareNum, Integer viewNum, Integer likeNum, Integer saveNum) {
        super(Picture.PICTURE);

        set(0, id);
        set(1, srcSite);
        set(2, srcUrl);
        set(3, url);
        set(4, name);
        set(5, savePath);
        set(6, yn);
        set(7, createTime);
        set(8, modifyTime);
        set(9, tag);
        set(10, type);
        set(11, desc);
        set(12, shareNum);
        set(13, viewNum);
        set(14, likeNum);
        set(15, saveNum);
    }
}
