package com.hjr.framework.appollo.spider.domain;

import java.util.Date;

public class CrawlResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.ID
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.SRC_URL
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private String srcUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.URL
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.TYPE
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.CONTENT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.YN
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private Byte yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.CREATE_TIME
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.MODIFY_TIME
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_RESULT.SRC_SITE
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    private String srcSite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.ID
     *
     * @return the value of CRAWL_RESULT.ID
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.ID
     *
     * @param id the value for CRAWL_RESULT.ID
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.SRC_URL
     *
     * @return the value of CRAWL_RESULT.SRC_URL
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public String getSrcUrl() {
        return srcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.SRC_URL
     *
     * @param srcUrl the value for CRAWL_RESULT.SRC_URL
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setSrcUrl(String srcUrl) {
        this.srcUrl = srcUrl == null ? null : srcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.URL
     *
     * @return the value of CRAWL_RESULT.URL
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.URL
     *
     * @param url the value for CRAWL_RESULT.URL
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.TYPE
     *
     * @return the value of CRAWL_RESULT.TYPE
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.TYPE
     *
     * @param type the value for CRAWL_RESULT.TYPE
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.CONTENT
     *
     * @return the value of CRAWL_RESULT.CONTENT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.CONTENT
     *
     * @param content the value for CRAWL_RESULT.CONTENT
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.YN
     *
     * @return the value of CRAWL_RESULT.YN
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.YN
     *
     * @param yn the value for CRAWL_RESULT.YN
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.CREATE_TIME
     *
     * @return the value of CRAWL_RESULT.CREATE_TIME
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.CREATE_TIME
     *
     * @param createTime the value for CRAWL_RESULT.CREATE_TIME
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.MODIFY_TIME
     *
     * @return the value of CRAWL_RESULT.MODIFY_TIME
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.MODIFY_TIME
     *
     * @param modifyTime the value for CRAWL_RESULT.MODIFY_TIME
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_RESULT.SRC_SITE
     *
     * @return the value of CRAWL_RESULT.SRC_SITE
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public String getSrcSite() {
        return srcSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_RESULT.SRC_SITE
     *
     * @param srcSite the value for CRAWL_RESULT.SRC_SITE
     *
     * @mbg.generated Sun May 13 13:58:09 CST 2018
     */
    public void setSrcSite(String srcSite) {
        this.srcSite = srcSite == null ? null : srcSite.trim();
    }
}