package com.hjr.framework.appollo.spider.domain;

import java.util.Date;

public class CrawlTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.ID
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.NAME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.SCHEDULE_TYPE
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Byte scheduleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.SCHEDULE_CRON
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private String scheduleCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.LAST_EXECUTE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Date lastExecuteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.NEXT_EXECUTE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Date nextExecuteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.YN
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Byte yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.CREATE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAWL_TASK.MODIFY_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.ID
     *
     * @return the value of CRAWL_TASK.ID
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.ID
     *
     * @param id the value for CRAWL_TASK.ID
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.NAME
     *
     * @return the value of CRAWL_TASK.NAME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.NAME
     *
     * @param name the value for CRAWL_TASK.NAME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.SCHEDULE_TYPE
     *
     * @return the value of CRAWL_TASK.SCHEDULE_TYPE
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Byte getScheduleType() {
        return scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.SCHEDULE_TYPE
     *
     * @param scheduleType the value for CRAWL_TASK.SCHEDULE_TYPE
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setScheduleType(Byte scheduleType) {
        this.scheduleType = scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.SCHEDULE_CRON
     *
     * @return the value of CRAWL_TASK.SCHEDULE_CRON
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public String getScheduleCron() {
        return scheduleCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.SCHEDULE_CRON
     *
     * @param scheduleCron the value for CRAWL_TASK.SCHEDULE_CRON
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setScheduleCron(String scheduleCron) {
        this.scheduleCron = scheduleCron == null ? null : scheduleCron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.LAST_EXECUTE_TIME
     *
     * @return the value of CRAWL_TASK.LAST_EXECUTE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Date getLastExecuteTime() {
        return lastExecuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.LAST_EXECUTE_TIME
     *
     * @param lastExecuteTime the value for CRAWL_TASK.LAST_EXECUTE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setLastExecuteTime(Date lastExecuteTime) {
        this.lastExecuteTime = lastExecuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.NEXT_EXECUTE_TIME
     *
     * @return the value of CRAWL_TASK.NEXT_EXECUTE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Date getNextExecuteTime() {
        return nextExecuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.NEXT_EXECUTE_TIME
     *
     * @param nextExecuteTime the value for CRAWL_TASK.NEXT_EXECUTE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setNextExecuteTime(Date nextExecuteTime) {
        this.nextExecuteTime = nextExecuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.YN
     *
     * @return the value of CRAWL_TASK.YN
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.YN
     *
     * @param yn the value for CRAWL_TASK.YN
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.CREATE_TIME
     *
     * @return the value of CRAWL_TASK.CREATE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.CREATE_TIME
     *
     * @param createTime the value for CRAWL_TASK.CREATE_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAWL_TASK.MODIFY_TIME
     *
     * @return the value of CRAWL_TASK.MODIFY_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAWL_TASK.MODIFY_TIME
     *
     * @param modifyTime the value for CRAWL_TASK.MODIFY_TIME
     *
     * @mbg.generated Wed Feb 20 21:00:42 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}