package com.hjr.framework.appollo.spider.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrawlDataParseRuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public CrawlDataParseRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TASK_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TASK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("TASK_ID =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("TASK_ID <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("TASK_ID >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_ID >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("TASK_ID <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_ID <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("TASK_ID in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("TASK_ID not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("TASK_ID between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_ID not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeIsNull() {
            addCriterion("SRC_PAGE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeIsNotNull() {
            addCriterion("SRC_PAGE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeEqualTo(String value) {
            addCriterion("SRC_PAGE_TYPE =", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeNotEqualTo(String value) {
            addCriterion("SRC_PAGE_TYPE <>", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeGreaterThan(String value) {
            addCriterion("SRC_PAGE_TYPE >", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_PAGE_TYPE >=", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeLessThan(String value) {
            addCriterion("SRC_PAGE_TYPE <", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeLessThanOrEqualTo(String value) {
            addCriterion("SRC_PAGE_TYPE <=", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeLike(String value) {
            addCriterion("SRC_PAGE_TYPE like", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeNotLike(String value) {
            addCriterion("SRC_PAGE_TYPE not like", value, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeIn(List<String> values) {
            addCriterion("SRC_PAGE_TYPE in", values, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeNotIn(List<String> values) {
            addCriterion("SRC_PAGE_TYPE not in", values, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeBetween(String value1, String value2) {
            addCriterion("SRC_PAGE_TYPE between", value1, value2, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andSrcPageTypeNotBetween(String value1, String value2) {
            addCriterion("SRC_PAGE_TYPE not between", value1, value2, "srcPageType");
            return (Criteria) this;
        }

        public Criteria andDataNameIsNull() {
            addCriterion("DATA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDataNameIsNotNull() {
            addCriterion("DATA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDataNameEqualTo(String value) {
            addCriterion("DATA_NAME =", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotEqualTo(String value) {
            addCriterion("DATA_NAME <>", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameGreaterThan(String value) {
            addCriterion("DATA_NAME >", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_NAME >=", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLessThan(String value) {
            addCriterion("DATA_NAME <", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLessThanOrEqualTo(String value) {
            addCriterion("DATA_NAME <=", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLike(String value) {
            addCriterion("DATA_NAME like", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotLike(String value) {
            addCriterion("DATA_NAME not like", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameIn(List<String> values) {
            addCriterion("DATA_NAME in", values, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotIn(List<String> values) {
            addCriterion("DATA_NAME not in", values, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameBetween(String value1, String value2) {
            addCriterion("DATA_NAME between", value1, value2, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotBetween(String value1, String value2) {
            addCriterion("DATA_NAME not between", value1, value2, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleIsNull() {
            addCriterion("DATA_PARSE_RULE is null");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleIsNotNull() {
            addCriterion("DATA_PARSE_RULE is not null");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleEqualTo(String value) {
            addCriterion("DATA_PARSE_RULE =", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleNotEqualTo(String value) {
            addCriterion("DATA_PARSE_RULE <>", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleGreaterThan(String value) {
            addCriterion("DATA_PARSE_RULE >", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_PARSE_RULE >=", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleLessThan(String value) {
            addCriterion("DATA_PARSE_RULE <", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleLessThanOrEqualTo(String value) {
            addCriterion("DATA_PARSE_RULE <=", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleLike(String value) {
            addCriterion("DATA_PARSE_RULE like", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleNotLike(String value) {
            addCriterion("DATA_PARSE_RULE not like", value, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleIn(List<String> values) {
            addCriterion("DATA_PARSE_RULE in", values, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleNotIn(List<String> values) {
            addCriterion("DATA_PARSE_RULE not in", values, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleBetween(String value1, String value2) {
            addCriterion("DATA_PARSE_RULE between", value1, value2, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andDataParseRuleNotBetween(String value1, String value2) {
            addCriterion("DATA_PARSE_RULE not between", value1, value2, "dataParseRule");
            return (Criteria) this;
        }

        public Criteria andYnIsNull() {
            addCriterion("YN is null");
            return (Criteria) this;
        }

        public Criteria andYnIsNotNull() {
            addCriterion("YN is not null");
            return (Criteria) this;
        }

        public Criteria andYnEqualTo(Byte value) {
            addCriterion("YN =", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotEqualTo(Byte value) {
            addCriterion("YN <>", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnGreaterThan(Byte value) {
            addCriterion("YN >", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnGreaterThanOrEqualTo(Byte value) {
            addCriterion("YN >=", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnLessThan(Byte value) {
            addCriterion("YN <", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnLessThanOrEqualTo(Byte value) {
            addCriterion("YN <=", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnIn(List<Byte> values) {
            addCriterion("YN in", values, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotIn(List<Byte> values) {
            addCriterion("YN not in", values, "yn");
            return (Criteria) this;
        }

        public Criteria andYnBetween(Byte value1, Byte value2) {
            addCriterion("YN between", value1, value2, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotBetween(Byte value1, Byte value2) {
            addCriterion("YN not between", value1, value2, "yn");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated do_not_delete_during_merge Sun May 13 14:54:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRAWL_DATA_PARSE_RULE
     *
     * @mbg.generated Sun May 13 14:54:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}