package com.hjr.framework.appollo.spider.domain;

import java.util.Date;

public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.ID
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.SRC_SITE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String srcSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.SRC_URL
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String srcUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.URL
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.NAME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.SAVE_PATH
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String savePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.YN
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Byte yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.CREATE_TIME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.MODIFY_TIME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.TAG
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.TYPE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.DESC
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.SHARE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Integer shareNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.VIEW_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Integer viewNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.LIKE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PICTURE.SAVE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    private Integer saveNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.ID
     *
     * @return the value of PICTURE.ID
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.ID
     *
     * @param id the value for PICTURE.ID
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.SRC_SITE
     *
     * @return the value of PICTURE.SRC_SITE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getSrcSite() {
        return srcSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.SRC_SITE
     *
     * @param srcSite the value for PICTURE.SRC_SITE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setSrcSite(String srcSite) {
        this.srcSite = srcSite == null ? null : srcSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.SRC_URL
     *
     * @return the value of PICTURE.SRC_URL
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getSrcUrl() {
        return srcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.SRC_URL
     *
     * @param srcUrl the value for PICTURE.SRC_URL
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setSrcUrl(String srcUrl) {
        this.srcUrl = srcUrl == null ? null : srcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.URL
     *
     * @return the value of PICTURE.URL
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.URL
     *
     * @param url the value for PICTURE.URL
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.NAME
     *
     * @return the value of PICTURE.NAME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.NAME
     *
     * @param name the value for PICTURE.NAME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.SAVE_PATH
     *
     * @return the value of PICTURE.SAVE_PATH
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getSavePath() {
        return savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.SAVE_PATH
     *
     * @param savePath the value for PICTURE.SAVE_PATH
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setSavePath(String savePath) {
        this.savePath = savePath == null ? null : savePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.YN
     *
     * @return the value of PICTURE.YN
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.YN
     *
     * @param yn the value for PICTURE.YN
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.CREATE_TIME
     *
     * @return the value of PICTURE.CREATE_TIME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.CREATE_TIME
     *
     * @param createTime the value for PICTURE.CREATE_TIME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.MODIFY_TIME
     *
     * @return the value of PICTURE.MODIFY_TIME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.MODIFY_TIME
     *
     * @param modifyTime the value for PICTURE.MODIFY_TIME
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.TAG
     *
     * @return the value of PICTURE.TAG
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.TAG
     *
     * @param tag the value for PICTURE.TAG
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.TYPE
     *
     * @return the value of PICTURE.TYPE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.TYPE
     *
     * @param type the value for PICTURE.TYPE
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.DESC
     *
     * @return the value of PICTURE.DESC
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.DESC
     *
     * @param desc the value for PICTURE.DESC
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.SHARE_NUM
     *
     * @return the value of PICTURE.SHARE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Integer getShareNum() {
        return shareNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.SHARE_NUM
     *
     * @param shareNum the value for PICTURE.SHARE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setShareNum(Integer shareNum) {
        this.shareNum = shareNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.VIEW_NUM
     *
     * @return the value of PICTURE.VIEW_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Integer getViewNum() {
        return viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.VIEW_NUM
     *
     * @param viewNum the value for PICTURE.VIEW_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setViewNum(Integer viewNum) {
        this.viewNum = viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.LIKE_NUM
     *
     * @return the value of PICTURE.LIKE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.LIKE_NUM
     *
     * @param likeNum the value for PICTURE.LIKE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PICTURE.SAVE_NUM
     *
     * @return the value of PICTURE.SAVE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public Integer getSaveNum() {
        return saveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PICTURE.SAVE_NUM
     *
     * @param saveNum the value for PICTURE.SAVE_NUM
     *
     * @mbg.generated Sun May 13 13:25:24 CST 2018
     */
    public void setSaveNum(Integer saveNum) {
        this.saveNum = saveNum;
    }
}