/*
 * This file is generated by jOOQ.
*/
package com.hjr.framework.appollo.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPicture extends Serializable {

    /**
     * Setter for <code>PUBLIC.PICTURE.ID</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>PUBLIC.PICTURE.ID</code>.
     */
    public Long getId();

    /**
     * Setter for <code>PUBLIC.PICTURE.SRC_SITE</code>.
     */
    public void setSrcSite(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.SRC_SITE</code>.
     */
    public String getSrcSite();

    /**
     * Setter for <code>PUBLIC.PICTURE.SRC_URL</code>.
     */
    public void setSrcUrl(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.SRC_URL</code>.
     */
    public String getSrcUrl();

    /**
     * Setter for <code>PUBLIC.PICTURE.URL</code>.
     */
    public void setUrl(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.URL</code>.
     */
    public String getUrl();

    /**
     * Setter for <code>PUBLIC.PICTURE.NAME</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.NAME</code>.
     */
    public String getName();

    /**
     * Setter for <code>PUBLIC.PICTURE.SAVE_PATH</code>.
     */
    public void setSavePath(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.SAVE_PATH</code>.
     */
    public String getSavePath();

    /**
     * Setter for <code>PUBLIC.PICTURE.YN</code>.
     */
    public void setYn(Byte value);

    /**
     * Getter for <code>PUBLIC.PICTURE.YN</code>.
     */
    public Byte getYn();

    /**
     * Setter for <code>PUBLIC.PICTURE.CREATE_TIME</code>.
     */
    public void setCreateTime(LocalDate value);

    /**
     * Getter for <code>PUBLIC.PICTURE.CREATE_TIME</code>.
     */
    public LocalDate getCreateTime();

    /**
     * Setter for <code>PUBLIC.PICTURE.MODIFY_TIME</code>.
     */
    public void setModifyTime(LocalDate value);

    /**
     * Getter for <code>PUBLIC.PICTURE.MODIFY_TIME</code>.
     */
    public LocalDate getModifyTime();

    /**
     * Setter for <code>PUBLIC.PICTURE.TAG</code>.
     */
    public void setTag(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.TAG</code>.
     */
    public String getTag();

    /**
     * Setter for <code>PUBLIC.PICTURE.TYPE</code>.
     */
    public void setType(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.TYPE</code>.
     */
    public String getType();

    /**
     * Setter for <code>PUBLIC.PICTURE.DESC</code>.
     */
    public void setDesc(String value);

    /**
     * Getter for <code>PUBLIC.PICTURE.DESC</code>.
     */
    public String getDesc();

    /**
     * Setter for <code>PUBLIC.PICTURE.SHARE_NUM</code>.
     */
    public void setShareNum(Integer value);

    /**
     * Getter for <code>PUBLIC.PICTURE.SHARE_NUM</code>.
     */
    public Integer getShareNum();

    /**
     * Setter for <code>PUBLIC.PICTURE.VIEW_NUM</code>.
     */
    public void setViewNum(Integer value);

    /**
     * Getter for <code>PUBLIC.PICTURE.VIEW_NUM</code>.
     */
    public Integer getViewNum();

    /**
     * Setter for <code>PUBLIC.PICTURE.LIKE_NUM</code>.
     */
    public void setLikeNum(Integer value);

    /**
     * Getter for <code>PUBLIC.PICTURE.LIKE_NUM</code>.
     */
    public Integer getLikeNum();

    /**
     * Setter for <code>PUBLIC.PICTURE.SAVE_NUM</code>.
     */
    public void setSaveNum(Integer value);

    /**
     * Getter for <code>PUBLIC.PICTURE.SAVE_NUM</code>.
     */
    public Integer getSaveNum();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPicture
     */
    public void from(com.hjr.framework.appollo.jooq.tables.interfaces.IPicture from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPicture
     */
    public <E extends com.hjr.framework.appollo.jooq.tables.interfaces.IPicture> E into(E into);
}
